### ISSUE TITLE
How can I use my custom package inside docker?

### ISSUE THREAD

**Issue by rohitkadam19** [bahmutov/demo-docker-cypress-included#1]
Hi @bahmutov,

I have created one custom npm package with name `@orgname/cypress-orgname-plugin`  where I added reusable actions as a cypress commands like login, logout, user creation etc.
I have added it in my `package.json` and it's published to internal npm registry.

So when I run command:
       `docker run -it -v $PWD:/e2e -w /e2e cypress/included:3.2.0` 

it gives me error:
```
The plugins file is missing or invalid.

Your `pluginsFile` is set to `/e2e/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js` or `.coffee` file.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.

 Error: Cannot find module '@orgname/cypress-orgname-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/e2e/cypress/plugins/index.js:13:13)
    at Object.<anonymous> (/e2e/cypress/plugins/index.js:23:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:118:15)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:14:25)
    at Object.<anonymous> (/root/.cache/Cypress/3.2.0/Cypress/resources/app/packages/server/lib/plugins/child/index.js:16:3)
```

To solve this, I started cypress container in interactive mode and tried to navigate to `node_modules/@orgname/cypress-orgname-plugin` but it failed with permission error.
So, I changed permissions of node_modules(777) and then started cypress container again in interactive mode. Ran `npm install @orgname/cypress-orgname-plugin --registry=<registry-url>` and then it worked fine.

This is not a cypress docker image problem but general file permission problem when mounting files to docker.

How can we solve this problem if someone wants use some other package?

**Comment by bahmutov** [comment]
Hi @rohitkadam19 so two things about loading custom code in this way
- Cypress was installed globally in the image, so it probably does not find the local NPM module - because you have not mapped the local `node_modules` folder into the container
- I would say that if you need custom plugins maybe it makes sense to build your own Docker image on top of `cypress/included`?

But I love your way of putting reusable commands into versioned internal NPM module, a great way to go

**Comment by rohitkadam19** [comment]
Hi @bahmutov,

Thanks for your response.
I took the second approach which will allow me to have control over change in cypress docker image and it worked with that. 

And this reusable commands into versioned NPM module is really working out for us.
